name : simple

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: indramuliasy/simple-indra:1.1
    ports:
      - "5000:3000"
    volumes:
      - vol-simple:/app/public/images/
volumes:
  vol-simple: